import {test} from 'node:test';import assert from 'node:assert/strict';import {readdirSync,readFileSync} from 'node:fs';import {resolve} from 'node:path';import {KIND,config} from '../lib/config.ts';
const dir=readdirSync('node_modules/.pnpm').find(x=>x.startsWith('miniflare@'));const {Miniflare}=await import(resolve('node_modules/.pnpm',dir,'node_modules/miniflare/dist/src/index.js'));
const files=readdirSync('dist/server',{recursive:true}).filter(x=>x.endsWith('.js')).sort((a,b)=>a==='index.js'?-1:b==='index.js'?1:0);
const mf=new Miniflare({modules:files.map(path=>({type:'ESModule',path:resolve('dist/server',path),contents:readFileSync('dist/server/'+path,'utf8')})),modulesRoot:resolve('dist/server'),compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],assets:{directory:resolve('dist/client'),binding:'ASSETS',routerConfig:{invoke_user_worker_ahead_of_assets:true,has_user_worker:true}}});
const db=await mf.getD1Database('DB');await db.exec(readFileSync('drizzle/'+readdirSync('drizzle').find(x=>x.endsWith('.sql')),'utf8').replaceAll('\n',' '));
const get=async()=>{const r=await mf.dispatchFetch('https://test.local/api/state');assert.equal(r.status,200);return await r.json()};
const post=async(body,origin='https://test.local')=>{const r=await mf.dispatchFetch('https://test.local/api/state',{method:'POST',headers:{origin,'content-type':'application/json','x-workbench-request':'1'},body:JSON.stringify(body)});return {status:r.status,data:await r.json()}};
const freshRecord=(entity,s,name)=>Object.fromEntries(entity.fields.map(f=>[f.key,f.key==='name'?name:f.type==='reference'?s[f.ref][0].id:f.type==='datetime'?new Date(Date.now()+f.default*3600000).toISOString():f.default]));
try{
 await test('database initialization and repeated reads preserve records',async()=>{const s=await get();assert.equal(s.kind,KIND);assert.equal(s.auditValid,true);assert(s.initialResult.rows.length>0);assert.equal((await get()).version,s.version)});
 await test('cross-origin writes rejected without data changes',async()=>{const s=await get();assert.equal((await post({action:'snapshot',version:s.version,parameters:s.initialParameters},'https://other.local')).status,403);assert.equal((await get()).version,s.version)});
 await test('invalid actions and unknown fields rejected',async()=>{const s=await get();assert.equal((await post({action:'unknown',version:s.version})).status,400);assert.equal((await post({action:'analyze',version:s.version,parameters:{...s.initialParameters,unknown:1}})).status,400)});
 await test('server analysis, saved snapshot and review note persist',async()=>{let s=await get();const r=await post({action:'analyze',version:s.version,parameters:s.initialParameters});assert.equal(r.status,200);assert(r.data.result.rows.length>0);assert.equal((await get()).version,s.version);assert.equal((await post({action:'snapshot',version:s.version,parameters:s.initialParameters})).status,200);s=await get();assert.equal(s.snapshots.length,1);assert.equal((await post({action:'review',version:s.version,snapshotId:s.snapshots[0].id,note:'Reviewed demonstration evidence; follow-up required.',status:'FOLLOW_UP'})).status,200);assert.equal((await get()).reviews.length,1)});
 await test('validated creation and editing read back saved values',async()=>{let s=await get();const entity=config.entities[0],record=freshRecord(entity,s,'Test '+crypto.randomUUID().slice(0,6));const added=await post({action:'add',version:s.version,entity:entity.key,record});assert.equal(added.status,200,JSON.stringify(added.data));s=await get();assert(s[entity.key].some(r=>r.id===added.data.result.id));const edited=await post({action:'edit',version:s.version,entity:entity.key,id:added.data.result.id,record:{...record,name:'Edited test record'}});assert.equal(edited.status,200);assert((await get())[entity.key].some(r=>r.name==='Edited test record'))});
 await test('out-of-range record rejected atomically',async()=>{const s=await get(),entity=config.entities[0],f=entity.fields.find(f=>['number','integer'].includes(f.type)),record=freshRecord(entity,s,'Invalid test');record[f.key]=f.min-1;assert.equal((await post({action:'add',version:s.version,entity:entity.key,record})).status,400);assert.equal((await get()).version,s.version)});
 await test('simultaneous writes have one winner and one conflict',async()=>{const s=await get();const body={action:'snapshot',version:s.version,parameters:s.initialParameters};const r=await Promise.all([post(body),post(body)]);assert.deepEqual(r.map(x=>x.status).sort(),[200,409]);assert.equal((await get()).version,s.version+1)});
 if(config.reservable){let planId;
 await test('simultaneous reservations cannot double-claim capacity',async()=>{const s=await get(),body={action:'reserve',version:s.version,parameters:s.initialParameters};const r=await Promise.all([post({...body,id:crypto.randomUUID()}),post({...body,id:crypto.randomUUID()})]);assert.deepEqual(r.map(x=>x.status).sort(),[200,409]);const next=await get();assert.equal(next.plans.length,1);planId=next.plans[0].id});
 await test('retry idempotency and cancellation settle once',async()=>{let s=await get();const replay=await post({action:'reserve',version:s.version,parameters:s.plans[0].parameters,id:planId});assert.equal(replay.status,200);assert.equal((await get()).plans.length,1);s=await get();assert.equal((await post({action:'settle',version:s.version,id:planId,status:'CANCELLED'})).status,200);s=await get();assert.equal((await post({action:'settle',version:s.version,id:planId,status:'CANCELLED'})).status,200);assert.equal((await post({action:'settle',version:s.version,id:planId,status:'CONFIRMED'})).status,409)});
 await test('confirmation and optional departure reconcile state',async()=>{let s=await get();const result=await post({action:'reserve',version:s.version,parameters:s.initialParameters,id:crypto.randomUUID()});assert.equal(result.status,200);const id=result.data.result.id;s=await get();assert.equal((await post({action:'settle',version:s.version,id,status:'CONFIRMED'})).status,200);s=await get();if(config.release){const entity=KIND==='shelterlink'?'facilities':'centres';assert(s[entity].some(r=>r.occupied>0));assert.equal((await post({action:'settle',version:s.version,id,status:'EXITED'})).status,200)}else assert(s.demands.some(r=>r.served>0))});
 }
 await test('linked audit hashes verify and detect changed evidence',async()=>{const s=await get();assert.equal(s.auditValid,true);s.events[0].detail='modified after recording';await db.prepare('UPDATE workspace SET content=? WHERE id=1').bind(JSON.stringify(s)).run();assert.equal((await get()).auditValid,false);assert.equal((await post({action:'snapshot',version:s.version,parameters:s.initialParameters})).status,409)});
 await test('built root renders branded private workspace',async()=>{const r=await mf.dispatchFetch('https://test.local/');assert.equal(r.status,200);const html=await r.text();assert(html.includes(config.title));assert(html.includes('Private demonstration workspace'))});
}finally{await mf.dispose()}
