import {test} from 'node:test';import assert from 'node:assert/strict';import {seed} from '../lib/seed.ts';import {KIND,config} from '../lib/config.ts';import {water,wages,shelters,cooling,heatIndex,civic,diagnose,food,analyze,reserve,settle} from '../lib/algorithms.ts';
const now=Date.now(),defaults=s=>Object.fromEntries(config.parameters.map(f=>[f.key,f.type==='reference'?s[f.ref][0].id:f.default]));
if(KIND==='watertrace'){
 test('unit conversion compares micrograms and milligrams consistently',()=>{const s=seed(KIND,now),p=defaults(s),r=water(s,p,now);assert.equal(r.rows[1].value,18);assert.equal(r.rows[1].unit,'mg/L');assert.equal(r.conflicts.length,1)});
 test('uncalibrated and unverified measurements excluded',()=>{const s=seed(KIND,now),r=water(s,defaults(s),now);assert.equal(r.rows.filter(x=>x.status==='Excluded').length,2);assert.equal(r.metrics[2][1],1)});
 test('incompatible units, duplicates and future times are explicit',()=>{const s=seed(KIND,now),p=defaults(s);s.readings.push({...s.readings[0],id:'duplicate'});s.readings[0].unit='NTU';s.readings[1].observedAt=new Date(now+86400000).toISOString();const r=water(s,p,now);assert(r.rows[0].issues.includes('Incompatible unit'));assert(r.rows[1].issues.includes('Future observation'));assert(r.rows.at(-1).issues.includes('Duplicate evidence'))});
 test('old readings excluded and tighter custom limits flag values',()=>{const s=seed(KIND,now),p=defaults(s);s.readings[0].observedAt=new Date(now-60*86400000).toISOString();const r=water(s,{...p,limit:1},now);assert(r.rows[0].issues.includes('Old observation'));assert.equal(r.rows[1].status,'Above custom limit')});
}
if(KIND==='wageproof'){
 test('overlap does not double-count worked minutes',()=>{const s=seed(KIND,now),p=defaults(s),withOverlap=wages(s,p);s.shifts.pop();const without=wages(s,p);assert.equal(withOverlap.rows.reduce((a,r)=>a+r.workedHours,0),without.rows.reduce((a,r)=>a+r.workedHours,0));assert(withOverlap.rows.some(r=>r.status.startsWith('Overlapping')))});
 test('breaks, regular and overtime pay use entered rates',()=>{const s=seed(KIND,now);s.shifts=[{id:'one',name:'shift',caseRef:'CASE-101',start:'2026-10-01T03:30:00Z',end:'2026-10-01T13:30:00Z',breakMinutes:60,verified:true}];const r=wages(s,defaults(s));assert.equal(r.rows[0].workedHours,9);assert.equal(r.rows[0].estimatedPaise,95000)});
 test('cross-midnight shift splits into fixed-offset workdays',()=>{const s=seed(KIND,now);s.shifts=[{name:'night',caseRef:'CASE-101',start:'2026-10-01T17:30:00Z',end:'2026-10-01T20:30:00Z',breakMinutes:0,verified:true}];const r=wages(s,defaults(s));assert.equal(r.rows.length,2);assert.equal(r.rows[0].workedHours,1);assert.equal(r.rows[1].workedHours,2)});
 test('unverified payments and shifts cannot support estimates',()=>{const s=seed(KIND,now);s.shifts.forEach(r=>r.verified=false);s.payments[0].verified=false;const r=wages(s,defaults(s));assert.equal(r.rows.length,0);assert.equal(r.metrics[1][1],0);assert.equal(r.excluded.length,3)});
}
if(KIND==='shelterlink'){
 test('consent and capability gates choose compatible capacity',()=>{const s=seed(KIND,now),r=shelters(s,defaults(s),now);assert.equal(r.recommendation.facilityId,'facility1');assert.equal(r.recommendation.quantity,3);assert.equal(r.blocked.length,2)});
 test('without consent no facility can be recommended',()=>{const s=seed(KIND,now);s.cases[0].consent=false;assert.equal(shelters(s,defaults(s),now).recommendation,null)});
 test('full, expired or distant capacity is excluded',()=>{const s=seed(KIND,now),p=defaults(s);s.facilities[0].available=0;assert.equal(shelters(s,p,now).recommendation,null);s.facilities[0].available=8;s.facilities[0].openUntil=new Date(now-1).toISOString();assert.equal(shelters(s,p,now).recommendation,null);s.facilities[0].openUntil=new Date(now+1e8).toISOString();assert.equal(shelters(s,{...p,maxDistance:.1},now).recommendation,null)});
}
if(KIND==='heatsafe'){
 test('Rothfusz regression reproduces a warm-weather reference',()=>assert(Math.abs(heatIndex(32.222222222,70)-41.0678)<.1));
 test('lower-exposure route can beat the shorter hot route',()=>{const s=seed(KIND,now),r=cooling(s,defaults(s),now);assert.equal(r.recommendation.facilityId,'centre1');assert.deepEqual(r.path.map(x=>x.id),['link2','link3']);assert.equal(r.metrics[1][1],16)});
 test('closed links, arrival windows and access constrain routes',()=>{const s=seed(KIND,now),p=defaults(s);s.links[1].closed=true;assert.deepEqual(cooling(s,p,now).path.map(x=>x.id),['link1']);s.centres[0].closesAt=new Date(now+5*60000).toISOString();assert.equal(cooling(s,p,now).recommendation,null)});
 test('bounded search rejects over-large graphs',()=>{const s=seed(KIND,now);for(let i=0;i<10;i++)s.nodes.push({id:'extra'+i});assert.throws(()=>cooling(s,defaults(s),now),/limit/)});
}
if(KIND==='civicevidence'){
 test('payments reconcile against approved values and progress',()=>{const s=seed(KIND,now),r=civic(s,defaults(s));assert.equal(r.rows[0].supportedPaise,10000000);assert(r.rows[0].status.includes('ahead'));assert(r.rows[1].status.includes('No verified'));assert.equal(r.budgets[0].overBudget,true)});
 test('latest verified cumulative observation is used, not summed',()=>{const s=seed(KIND,now);s.evidence.push({...s.evidence[0],id:'new',quantity:150,observedAt:new Date(now).toISOString()});assert.equal(civic(s,defaults(s)).rows[0].supportedPaise,15000000)});
 test('unverified observations are excluded and supported value capped',()=>{const s=seed(KIND,now);s.evidence[0].quantity=999;assert.equal(civic(s,defaults(s)).rows[0].supportedPaise,20000000);s.evidence[0].verified=false;assert.equal(civic(s,defaults(s)).rows[0].supportedPaise,0)});
 test('excess paid values remain visible as review questions',()=>{const s=seed(KIND,now);s.payments[0].amountPaise=30000000;assert(civic(s,defaults(s)).rows[0].status.includes('above approval'))});
}
if(KIND==='repaircommons'){
 test('posterior normalized and invalid observations rejected',()=>{const s=seed(KIND,now),p=defaults(s),r=diagnose(s,p);assert(Math.abs(r.rows.reduce((a,x)=>a+x.probabilityPercent,0)-100)<.02);assert.throws(()=>diagnose(s,{...p,answers:'unknown=yes'}));assert.throws(()=>diagnose(s,{...p,answers:'no-power=yes,no-power=no'}))});
 test('positive and negative evidence change fault ranking',()=>{const s=seed(KIND,now),p=defaults(s);const humming=diagnose(s,{...p,answers:'humming=yes'});assert.equal(humming.rows[0].id,'fault2');const quiet=diagnose(s,{...p,answers:'humming=no'});assert.notEqual(quiet.rows[0].id,'fault2')});
 test('next question has nonnegative expected information gain',()=>{const s=seed(KIND,now),r=diagnose(s,defaults(s));assert.equal(r.questions[0].symptom,'humming');assert(r.questions[0].informationBits>0)});
 test('parts require compatibility, evidence, stock and budget',()=>{const s=seed(KIND,now),p=defaults(s);assert.equal(diagnose(s,p).parts.length,2);assert.equal(diagnose(s,{...p,maxPricePaise:1}).parts.length,0);s.parts[0].available=0;assert.equal(diagnose(s,p).parts.length,1)});
}
if(KIND==='foodrescue-dispatch'){
 test('complete itinerary respects pickup precedence and vehicle load',()=>{const s=seed(KIND,now),p=defaults(s),r=food(s,p,now);assert(r.recommendation);let load=0;for(const e of r.rows){load+=e.action==='Pickup'?e.quantity:-e.quantity;assert(load>=0&&load<=p.capacity)}assert.equal(load,0);assert.equal(r.rows.length,r.lines.length*2);assert(r.rows.at(-1).minutes<=p.maxMinutes)});
 test('unverified and cold-chain incompatible lots excluded',()=>{const s=seed(KIND,now),p=defaults(s),r=food(s,{...p,coldChain:false},now);assert(r.lines.every(l=>l.stockId==='supply1'))});
 test('recipient closure and lot expiry prevent delivery',()=>{const s=seed(KIND,now),p=defaults(s);s.demands.forEach(x=>x.closesAt=new Date(now+100).toISOString());assert.equal(food(s,p,now).recommendation,null);s.demands.forEach(x=>x.closesAt=new Date(now+86400000).toISOString());s.supplies.forEach(x=>x.expiresAt=new Date(now+100).toISOString());assert.equal(food(s,p,now).recommendation,null)});
 test('diet restrictions and demand cap every planned line',()=>{const s=seed(KIND,now),p=defaults(s),r=food(s,p,now);for(const line of r.lines){const a=s.supplies.find(x=>x.id===line.stockId),b=s.demands.find(x=>x.id===line.requestId);assert.equal(a.diet,b.diet)}for(const d of s.demands)assert(r.lines.filter(l=>l.requestId===d.id).reduce((a,l)=>a+l.quantity,0)<=d.quantity)});
}
if(config.reservable){
 test('reservation replay and cancellation preserve capacity',()=>{const s=seed(KIND,now),p=defaults(s),before=JSON.stringify(s),plan=reserve(KIND,s,'idempotent',p,now);reserve(KIND,s,'idempotent',p,now);assert.equal(s.plans.length,1);settle(KIND,s,plan.id,'CANCELLED');assert.equal(settle(KIND,s,plan.id,'CANCELLED'),false);const initial=JSON.parse(before);if(KIND==='foodrescue-dispatch'){assert.deepEqual(s.supplies,initial.supplies);assert.deepEqual(s.demands,initial.demands)}else{const key=KIND==='shelterlink'?'facilities':'centres';assert.deepEqual(s[key],initial[key])}assert.throws(()=>settle(KIND,s,plan.id,'CONFIRMED'))});
 test('confirmation settles once; occupied space can be released',()=>{const s=seed(KIND,now),p=defaults(s),plan=reserve(KIND,s,'confirmed',p,now);settle(KIND,s,plan.id,'CONFIRMED');assert.equal(settle(KIND,s,plan.id,'CONFIRMED'),false);assert.throws(()=>settle(KIND,s,plan.id,'CANCELLED'));if(config.release){settle(KIND,s,plan.id,'EXITED');const key=KIND==='shelterlink'?'facilities':'centres';assert.equal(s[key].find(x=>x.id===plan.result.recommendation.facilityId).occupied,0)}else assert(s.demands.some(x=>x.served>0))});
}
