"use client";
import {useState,useEffect,useCallback,useRef} from 'react';import {Button} from '@/components/ui/button';import {Input} from '@/components/ui/input';import {Activity,ClipboardList,Archive,ShieldCheck,RefreshCw,Download,Plus,Check,X,ArrowUpRight,Search,FlaskConical,HandCoins,House,Sun,Landmark,Wrench,Truck} from 'lucide-react';import {config,KIND} from '@/lib/config';
const icons:any={watertrace:FlaskConical,wageproof:HandCoins,shelterlink:House,heatsafe:Sun,civicevidence:Landmark,repaircommons:Wrench,'foodrescue-dispatch':Truck};
const money=(v:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(v/100);
function dateInput(v:string){const d=new Date(v);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
function initialFields(fields:any[],s:any){return Object.fromEntries(fields.map(f=>[f.key,f.type==='reference'?(s[f.ref]?.[0]?.id??''):f.type==='datetime'?new Date(Date.now()+f.default*3600000).toISOString():f.default]))}
function Field({f,value,onChange,s}:any){return <label className={'field '+(f.type==='boolean'?'checkbox':'')}><span>{f.label}{f.type==='datetime'&&<small>Local time</small>}</span>{f.type==='boolean'?<input type="checkbox" checked={!!value} onChange={e=>onChange(e.target.checked)}/>:['reference','select'].includes(f.type)?<select required value={value??''} onChange={e=>onChange(e.target.value)}>{f.type==='reference'&&!s[f.ref]?.length&&<option value="">No records available</option>}{(f.type==='reference'?s[f.ref]:f.options)?.map((o:any)=><option key={o.id??o} value={o.id??o}>{o.name??o}</option>)}</select>:f.key==='content'||f.key==='guidance'?<textarea required maxLength={2000} value={value??''} onChange={e=>onChange(e.target.value)}/>:<Input required={f.key!=='answers'} maxLength={200} type={['number','integer'].includes(f.type)?'number':f.type==='datetime'?'datetime-local':'text'} step={f.type==='integer'?1:f.type==='number'?'any':undefined} min={f.min} max={f.max} value={f.type==='datetime'?dateInput(value):value??''} onChange={e=>onChange(['number','integer'].includes(f.type)?e.target.value===''?'':Number(e.target.value):f.type==='datetime'?e.target.value?new Date(e.target.value).toISOString():new Date().toISOString():e.target.value)}/>}</label>}
function pretty(k:string,v:any,s:any):any{if(v===undefined||v===null)return '—';if(k.toLowerCase().endsWith('paise'))return money(v);if(typeof v==='boolean')return v?'Yes':'No';if(Array.isArray(v))return v.join(' · ')||'—';if(k.endsWith('At')||k==='start'||k==='end'||k.endsWith('Until'))return new Date(v).toLocaleString();if(k.endsWith('Id'))return config.entities.flatMap((e:any)=>s[e.key]||[]).find((r:any)=>r.id===v)?.name??v;return String(v)}
function Table({rows,columns,s,onEdit}:any){return <div className="table-wrap"><table><thead><tr>{columns.map((c:string)=><th key={c}>{c.replace(/([A-Z])/g,' $1')}</th>)}{onEdit&&<th>Action</th>}</tr></thead><tbody>{rows.map((r:any,i:number)=><tr key={r.id??i}>{columns.map((c:string)=><td key={c} className={c==='status'?'status-cell':''}>{pretty(c,r[c],s)}</td>)}{onEdit&&<td><Button variant="outline" className="small-button" onClick={()=>onEdit(r)}>Edit</Button></td>}</tr>)}</tbody></table>{!rows.length&&<p className="empty">No matching records yet.</p>}</div>}
export default function Workbench(){const [s,setS]=useState<any>(null),[parameters,setParameters]=useState<any>({}),[result,setResult]=useState<any>(null),[tab,setTab]=useState('work'),[version,setVersion]=useState(-1),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[entityKey,setEntityKey]=useState(config.entities[0].key),[record,setRecord]=useState<any>({}),[editId,setEditId]=useState(''),[search,setSearch]=useState(''),[reviewId,setReviewId]=useState(''),[note,setNote]=useState(''),[reviewStatus,setReviewStatus]=useState('FOLLOW_UP');const loaded=useRef(false),reservationKey=useRef('');const Brand=icons[KIND];
 const load=useCallback(async()=>{const r=await fetch('/api/state',{cache:'no-store'}),d:any=await r.json();if(!r.ok)throw new Error(d.error);setS(d);if(!loaded.current){loaded.current=true;setParameters(d.initialParameters);setResult(d.initialResult);setVersion(d.version);setRecord(initialFields(config.entities[0].fields,d))}return d},[]);
 useEffect(()=>{load().catch(e=>setError(e.message))},[load]);
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const life=new AbortController();Promise.resolve(ctx.registerTool({name:'read_workspace',title:'Read '+config.title+' workspace',description:'Read persisted records and refresh the visible workspace.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:any)=>{if(Object.keys(input??{}).length)throw new Error('No arguments accepted');const d=await load();return {project:KIND,version:d.version,records:Object.fromEntries(config.entities.map((e:any)=>[e.key,d[e.key].length])),auditValid:d.auditValid}}},{signal:life.signal})).catch(console.error);return()=>life.abort()},[load]);
 const call=async(body:any)=>{const r=await fetch('/api/state',{method:'POST',headers:{'content-type':'application/json','x-workbench-request':'1'},body:JSON.stringify(body)}),d:any=await r.json();if(!r.ok)throw new Error(d.error);return d};
 async function action(body:any,message?:string){setBusy(true);setError('');setNotice('');try{const d=await call({...body,version:s.version});if(body.action==='analyze'){setResult(d.result);setVersion(d.version)}else{await load();setVersion(-1);if(message)setNotice(message)}return d}catch(e:any){setError(e.message);if(e.message.includes('changed')||e.message.includes('first')){await load();setVersion(-1)}return null}finally{setBusy(false)}}
 const entity=config.entities.find((e:any)=>e.key===entityKey);const updateParams=(key:string,v:any)=>{setParameters({...parameters,[key]:v});setVersion(-1);reservationKey.current=''};
 const switchEntity=(key:string)=>{setEntityKey(key);setEditId('');setSearch('');setRecord(initialFields(config.entities.find((e:any)=>e.key===key).fields,s))};
 const refresh=()=>{setError('');load().then(()=>{setVersion(-1);setNotice('Workspace refreshed. Calculate again to use the latest records.')}).catch(e=>setError(e.message))};
 const exportJson=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(s,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=KIND+'-workspace.json';a.click();URL.revokeObjectURL(url)};
 const exportCsv=()=>{const cols=entity.columns,rows=[cols,...s[entity.key].map((r:any)=>cols.map((c:string)=>pretty(c,r[c],s)))];const text=rows.map((row:any[])=>row.map(v=>'"'+String(v).replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=KIND+'-'+entityKey+'.csv';a.click();URL.revokeObjectURL(url)};
 return <div className={'app '+KIND} style={{'--accent':config.accent} as React.CSSProperties}><aside><a href="/" className="brand"><Brand/><span>{config.title}<small>{config.tag}</small></span></a><nav aria-label="Workspace">{[['work',config.reservable?'Plan & match':'Analyze evidence',Activity],['records','Records',ClipboardList],['history',config.reservable?'Reservations & history':'Saved reports',Archive],['method','Method & scope',ShieldCheck]].map(([id,label,Icon]:any)=><Button key={id} className={'nav-item '+(tab===id?'active':'')} variant="ghost" onClick={()=>setTab(id)}><Icon size={18}/>{label}</Button>)}</nav><div className="aside-note"><ShieldCheck size={20}/><p>Private demonstration workspace<small>Fictional records · shared state</small></p></div></aside>
 <main><header><div><span className="eyebrow">{config.tag}</span><h1>{tab==='work'?config.heading:tab==='records'?'Record register':tab==='history'?'Workflow history':'Method & scope'}</h1></div><div className="header-actions"><span className="revision">Revision {s?.version??'—'}</span><Button className="secondary" variant="outline" disabled={busy} onClick={refresh}><RefreshCw size={16}/>Refresh</Button></div></header>{error&&<div role="alert" className="message error">{error}</div>}{notice&&<div role="status" className="message success">{notice}</div>}
 {!s?<section className="panel"><p>{error?'Workspace unavailable. Use Refresh to retry.':'Loading saved records…'}</p></section>:<>
 {tab==='work'&&<><p className="intro">{config.intro}</p><div className="metrics">{(result?.metrics??[]).map(([label,value]:any)=><div className="metric" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="work-layout"><section className="panel controls"><h2>{config.reservable?'Planning constraints':'Analysis assumptions'}</h2><form onSubmit={e=>{e.preventDefault();action({action:'analyze',parameters})}}>{config.parameters.map((f:any)=><Field key={f.key} f={f} value={parameters[f.key]} onChange={(v:any)=>updateParams(f.key,v)} s={s}/>)}<Button className="primary" type="submit" disabled={busy}>{busy?'Working…':'Calculate'}</Button></form><p className="muted">{version===s.version?'Calculated from the current revision.':'Inputs or records changed. Calculate before saving or reserving.'}</p></section><section className="panel result-surface"><div className="section-head"><h2>{KIND==='repaircommons'?'Fault hypotheses':KIND==='foodrescue-dispatch'?'Vehicle itinerary':KIND==='heatsafe'?'Cooling route':KIND==='shelterlink'?'Referral candidates':'Evidence overview'}</h2><span className="pill">{version===s.version?'Current calculation':'Previous calculation'}</span></div>{result&&<><Visualization s={s} r={result} p={parameters}/><p className="explanation">{result.explanation}</p><div className="result-actions"><Button variant="outline" className="secondary" disabled={busy||version!==s.version} onClick={()=>action({action:'snapshot',parameters},'Analysis snapshot saved.')}>Save report</Button>{config.reservable&&<Button className="primary" disabled={busy||version!==s.version||!result.recommendation} onClick={async()=>{reservationKey.current ||= crypto.randomUUID();const saved=await action({action:'reserve',parameters,id:reservationKey.current},'Reservation saved. Open history to confirm or cancel.');if(saved)reservationKey.current=''}}>Reserve recommendation</Button>}</div></>}</section></div>
 {result&&<section className="panel"><div className="section-head"><h2>{KIND==='wageproof'?'Workday reconciliation':KIND==='watertrace'?'Measurement decisions':'Detailed results'}</h2><span className="muted">Amounts in paise are displayed as rupees.</span></div><Table rows={result.rows??[]} columns={result.columns??[]} s={s}/></section>}
 {result?.conflicts?.length>0&&<section className="panel"><h2>Conflicting measurements</h2><Table rows={result.conflicts} columns={['sample','median','spreadPercent','sources']} s={s}/></section>}
 {result?.excluded?.length>0&&<section className="panel"><h2>Excluded evidence</h2><Table rows={result.excluded} columns={['reference','reason']} s={s}/></section>}
 {result?.budgets&&<section className="panel"><h2>Budget reconciliation</h2><Table rows={result.budgets} columns={['project','budgetPaise','approvedPaise','overBudget']} s={s}/></section>}
 {KIND==='repaircommons'&&result&&<div className="lower-grid"><section className="panel"><h2>Next useful questions</h2>{result.questions.map((q:any)=><div className="question" key={q.symptom}><strong>{q.symptom}</strong><small>{q.informationBits} expected information bits</small><div className="result-actions">{['yes','no'].map(answer=><Button className="secondary" variant="outline" key={answer} disabled={busy} onClick={()=>{const p={...parameters,answers:[parameters.answers,q.symptom+'='+answer].filter(Boolean).join(',')};setParameters(p);action({action:'analyze',parameters:p})}}>{answer==='yes'?'Observed':'Not observed'}</Button>)}</div></div>)}{!result.questions.length&&<p>All known symptoms have been considered.</p>}</section><section className="panel"><h2>Compatible parts within budget</h2><Table rows={result.parts} columns={['name','fault','pricePaise','available']} s={s}/></section></div>}
 </>}
 {tab==='records'&&<><section className="panel"><div className="section-head"><div className="entity-tabs">{config.entities.map((e:any)=><Button className={entityKey===e.key?'primary':'secondary'} variant="outline" key={e.key} onClick={()=>switchEntity(e.key)}>{e.label}</Button>)}</div><Button className="secondary" variant="outline" onClick={exportCsv}><Download size={16}/>Export CSV</Button></div><label className="search"><Search size={17}/><Input aria-label="Search visible records" placeholder="Search these records" value={search} onChange={e=>setSearch(e.target.value)}/></label><Table rows={s[entityKey].filter((r:any)=>entity.columns.some((key:string)=>String(r[key]??'').toLowerCase().includes(search.toLowerCase())))} columns={entity.columns} s={s} onEdit={(r:any)=>{setEditId(r.id);setRecord(Object.fromEntries(entity.fields.map((f:any)=>[f.key,r[f.key]])));setNotice('Editing '+r.name+'. The original values remain in the activity record.')}}/></section><section className="panel"><div className="section-head"><h2>{editId?'Edit':'Add'} {entity.label.toLowerCase()}</h2>{editId&&<Button className="secondary" variant="outline" onClick={()=>{setEditId('');setRecord(initialFields(entity.fields,s))}}>Start a new record</Button>}</div><form onSubmit={async e=>{e.preventDefault();const saved=await action({action:editId?'edit':'add',entity:entityKey,record,...(editId?{id:editId}:{})},'Record saved.');if(saved){setEditId('');setRecord(initialFields(entity.fields,s))}}}><div className="form-grid">{entity.fields.map((f:any)=><Field key={f.key} f={f} value={record[f.key]} onChange={(v:any)=>setRecord({...record,[f.key]:v})} s={s}/>)}</div><Button className="primary" type="submit" disabled={busy}><Plus size={16}/>Save record</Button></form></section></>}
 {tab==='history'&&<>{config.reservable&&<section className="panel"><h2>Reservation lifecycle</h2>{!s.plans.length&&<p className="muted">Reserve an eligible recommendation from the planning desk.</p>}{s.plans.map((p:any)=><article className="reservation" key={p.id}><div className="section-head"><div><span className="pill">{p.status}</span><h3>{p.result.metrics[0]?.[1]} {KIND==='foodrescue-dispatch'?'units in a planned route':KIND==='shelterlink'?'people in the referral':'route options considered'}</h3><small>{new Date(p.createdAt).toLocaleString()} · {p.id.slice(0,8)}</small></div><div className="result-actions">{p.status==='RESERVED'&&<><Button className="primary" disabled={busy} onClick={()=>action({action:'settle',id:p.id,status:'CONFIRMED'},config.release?'Arrival confirmed; spaces are occupied.':'Delivery recorded; reserved demand is fulfilled.')}><Check size={16}/>{config.release?'Confirm arrival':'Mark delivered'}</Button><Button className="secondary" variant="outline" disabled={busy} onClick={()=>action({action:'settle',id:p.id,status:'CANCELLED'},'Reservation cancelled; capacity released.')}><X size={16}/>Cancel</Button></>}{config.release&&p.status==='CONFIRMED'&&<Button className="secondary" variant="outline" disabled={busy} onClick={()=>action({action:'settle',id:p.id,status:'EXITED'},'Departure recorded; occupied spaces released.')}>Record departure</Button>}</div></div><details><summary>Inspect reserved recommendation</summary><pre>{JSON.stringify(p.result.recommendation,null,2)}</pre></details></article>)}</section>}
 <section className="panel"><h2>Saved analysis snapshots</h2>{!s.snapshots.length&&<p className="muted">Save a calculated report to retain its result and assumptions.</p>}{s.snapshots.map((r:any)=><article className="snapshot" key={r.id}><div className="section-head"><strong>{new Date(r.createdAt).toLocaleString()}</strong><span className="pill">{r.id.slice(0,8)}</span></div><p>{r.result.explanation}</p><details><summary>View saved inputs and result</summary><pre>{JSON.stringify({parameters:r.parameters,result:r.result},null,2)}</pre></details><Button className="secondary" variant="outline" onClick={()=>setReviewId(r.id)}>Add review note</Button>{s.reviews.filter((review:any)=>review.snapshotId===r.id).map((review:any)=><p className="review-note" key={review.id}><strong>{review.status.replaceAll('_',' ')}</strong> · {review.note}</p>)}</article>)}</section>
 {reviewId&&<section className="panel"><h2>Review saved report {reviewId.slice(0,8)}</h2><form onSubmit={async e=>{e.preventDefault();const saved=await action({action:'review',snapshotId:reviewId,note,status:reviewStatus},'Review note saved.');if(saved){setReviewId('');setNote('')}}}><label className="field"><span>Review status</span><select value={reviewStatus} onChange={e=>setReviewStatus(e.target.value)}><option value="FOLLOW_UP">Follow-up needed</option><option value="REVIEWED">Reviewed</option></select></label><label className="field"><span>Evidence / follow-up note</span><textarea required minLength={5} maxLength={1000} value={note} onChange={e=>setNote(e.target.value)}/></label><Button className="primary" type="submit" disabled={busy}>Save review</Button></form></section>}
 <section className="panel"><div className="section-head"><h2>Linked activity record</h2><div className="result-actions"><span className={'pill '+(!s.auditValid?'warn':'')}>{s.auditValid?'Hash links verified':'Hash mismatch — review'}</span><Button className="secondary" variant="outline" onClick={exportJson}><Download size={16}/>Export workspace JSON</Button></div></div>{!s.events.length&&<p className="muted">No changes recorded yet.</p>}{[...s.events].reverse().map((event:any)=><div className="event" key={event.id}><Activity size={16}/><div><strong>{event.action}</strong><small>{new Date(event.createdAt).toLocaleString()} · {event.actor}</small><details><summary>Inspect event and hash</summary><pre>{JSON.stringify(event,null,2)}</pre></details></div></div>)}</section></>}
 {tab==='method'&&<section className="panel method"><h2>{config.title}: method</h2><p>{config.method}</p><h3>Demonstration scope</h3><p>{config.scope}</p><h3>Persistence and simultaneous actions</h3><p>A revision check atomically saves related records and workflow changes. A stale revision is rejected, and reservations are recomputed on the server. Retried reservation IDs cannot claim capacity twice.</p><h3>Evidence history</h3><p>Every saved mutation links to the previous event with SHA-256. This detects changed entries when the chain is retained; it is not externally notarized and cannot protect against a database administrator rewriting the whole chain. The private platform boundary controls access.</p><h3>Bounded portfolio workspace</h3><p>Up to 100 records per type, 100 snapshots, 100 reservations, 300 mutations and 1.8 MB of data. Heat routes and dispatch searches have stricter limits stated in their methods. No live external data, uploads or outbound messages are included.</p><h3>Verification</h3><p>Domain unit tests, database-backed request tests, TypeScript and Worker builds are included in the source. Browser interaction and WebMCP validation are unavailable in this environment.</p>{config.sources?.length>0&&<><h3>Primary background sources</h3>{config.sources.map(([label,url]:any)=><p key={url}><a href={url} target="_blank" rel="noreferrer">{label}</a></p>)}</>}</section>}
 </>}
 <footer>{config.title} / Engineering workbench<span>Fictional demonstration data</span></footer></main></div>
}
function Visualization({s,r,p}:any){
 if(KIND==='heatsafe'){const chosen=new Set((r.path??[]).map((l:any)=>l.id));return <svg viewBox="0 0 650 380" className="graph" role="img" aria-label="Fictional route network; detailed measurements appear in results"><rect width="650" height="380" fill="#f4f7fa"/>{s.links.map((l:any)=>{const a=s.nodes.find((n:any)=>n.id===l.fromId),b=s.nodes.find((n:any)=>n.id===l.toId);return <g key={l.id}><line x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke={chosen.has(l.id)?config.accent:'#a1b0ba'} strokeWidth={chosen.has(l.id)?7:3} strokeDasharray={l.closed?'6 5':undefined}/><text x={(a.x+b.x)/2} y={(a.y+b.y)/2-8} className="edge-label">{l.minutes} min · {l.temperature}°C</text></g>})}{s.nodes.map((n:any)=><g key={n.id}><circle cx={n.x} cy={n.y} r="9" fill="#172e41"/><text x={n.x} y={n.y+28} textAnchor="middle" className="node-label">{n.name}</text></g>)}</svg>}
 if(KIND==='shelterlink'){const c=s.cases.find((c:any)=>c.id===p.caseId);const points=[...s.facilities,...(c?[c]:[])];const xs=points.map(p=>p.x),ys=points.map(p=>p.y),xmin=Math.min(...xs)-1,xmax=Math.max(...xs)+1,ymin=Math.min(...ys)-1,ymax=Math.max(...ys)+1;return <><svg viewBox="0 0 650 330" className="graph" role="img" aria-label="Pseudonymous facilities on an abstract coordinate schematic"><rect width="650" height="330" fill="#f4f7fa"/>{points.map(p=><g key={p.id}><circle cx={40+(p.x-xmin)/(xmax-xmin)*560} cy={35+(p.y-ymin)/(ymax-ymin)*240} r={p.id===c?.id?12:8} fill={p.id===r.recommendation?.facilityId?config.accent:'#172e41'}/><text x={40+(p.x-xmin)/(xmax-xmin)*560} y={65+(p.y-ymin)/(ymax-ymin)*240} textAnchor="middle" className="node-label">{p.name}</text></g>)}</svg><p className="muted">Abstract coordinates only; no confidential shelter address is stored.</p></>}
 if(KIND==='foodrescue-dispatch'){return <div className="itinerary">{r.path?.length?r.path.map((stop:any,i:number)=><div className="stop" key={i}><span>{i+1}</span><div><strong>{stop.action} · {stop.name}</strong><small>{stop.quantity} units · {stop.minutes} minutes after departure</small></div></div>):<p className="empty">No complete itinerary meets the current constraints.</p>}</div>}
 if(KIND==='repaircommons')return <div className="bars">{r.rows.map((row:any)=><div className="bar-row" key={row.id}><div><strong>{row.fault}</strong><span>{row.probabilityPercent}%</span></div><div className="bar"><i style={{width:row.probabilityPercent+'%'}}/></div><small>{row.status}</small></div>)}</div>;
 if(KIND==='civicevidence')return <div className="bars">{r.rows.map((row:any)=><div className="bar-row" key={row.id}><strong>{row.milestone}</strong><div className="comparison"><label>Observed value</label><div className="bar"><i style={{width:Math.min(100,row.supportedPaise/row.approvedPaise*100)+'%'}}/></div><span>{money(row.supportedPaise)}</span><label>Recorded payments</label><div className="bar"><i className="dark" style={{width:Math.min(100,row.paidPaise/row.approvedPaise*100)+'%'}}/></div><span>{money(row.paidPaise)}</span></div></div>)}</div>;
 if(KIND==='wageproof')return <div className="bars">{r.rows.map((row:any)=><div className="bar-row" key={row.day}><div><strong>{row.day}</strong><span>{row.workedHours} hours</span></div><div className="bar stacked"><i className="dark" style={{width:row.regularHours/24*100+'%'}}/><i style={{width:row.overtimeHours/24*100+'%'}}/></div><small>Regular {row.regularHours}h · overtime {row.overtimeHours}h · {money(row.estimatedPaise)}</small></div>)}<p className="muted">Each track represents 24 hours in the configured workday offset.</p></div>;
 return <div className="reading-grid">{r.rows.map((row:any)=><article key={row.id} className={'reading '+(row.status==='Within custom limit'?'':'flagged')}><small>{row.sample} / {row.source}</small><strong>{row.value}<span>{row.unit}</span></strong><p>{row.status}</p>{row.issues.length>0&&<small>{row.issues.join(' · ')}</small>}</article>)}</div>
}
