import {z} from 'zod';import {analyze,reserve,settle} from './algorithms';import {config,KIND} from './config';import {seed} from './seed';
export {seed};export class Failure extends Error{status:number;constructor(status:number,message:string){super(message);this.status=status}}
export function defaults(fields:any[],state:any,now=Date.now()){return Object.fromEntries(fields.map(f=>[f.key,f.type==='reference'?(state[f.ref]?.[0]?.id??''):f.type==='datetime'?new Date(now+f.default*3600000).toISOString():f.default]))}
export function validate(fields:any[],data:any,state:any){const shape:Record<string,any>={};for(const f of fields){let v:any;switch(f.type){case 'number':case 'integer':v=z.number().finite().min(f.min??-1e9).max(f.max??1e9);if(f.type==='integer')v=v.int();break;case 'boolean':v=z.boolean();break;case 'datetime':v=z.string().datetime();break;case 'select':v=z.enum(f.options);break;case 'reference':v=z.string().refine(x=>state[f.ref]?.some((r:any)=>r.id===x),'Unknown reference');break;default:v=z.string().trim().min(f.key==='answers'?0:1).max(f.key==='content'?2000:200)}shape[f.key]=v}return z.object(shape).strict().parse(data)}
function verifyRecord(entity:string,record:any,state:any,existingId?:string){
 const duplicate=(keys:string[])=>state[entity].some((r:any)=>r.id!==existingId&&keys.every(k=>r[k]===record[k]));
 if(KIND==='watertrace'&&duplicate(['name','source','analyte','observedAt']))throw new Failure(409,'This measurement reference already exists');
 if(KIND==='wageproof'){if(entity==='shifts'){const duration=Date.parse(record.end)-Date.parse(record.start);if(duration<=0||duration>24*3600000||record.breakMinutes*60000>=duration)throw new Failure(400,'Shift must last 0–24 hours with a shorter break')}if(entity==='payments'&&duplicate(['name']))throw new Failure(409,'Payment reference already exists')}
 if(KIND==='shelterlink'&&entity==='cases'&&existingId&&state.cases.find((r:any)=>r.id===existingId).status!=='ACTIVE')throw new Failure(409,'An active referral must be settled before editing its case');
 if(KIND==='heatsafe'){if(entity==='nodes'&&state.nodes.length>=10&&!existingId)throw new Failure(409,'Demo limit: 10 locations');if(entity==='links'){if(record.fromId===record.toId)throw new Failure(400,'A connection needs two different locations');if(state.links.length>=30&&!existingId)throw new Failure(409,'Demo limit: 30 connections')}if(entity==='centres'&&Date.parse(record.closesAt)<=Date.parse(record.opensAt))throw new Failure(400,'Closing must follow opening')}
 if(KIND==='civicevidence'&&entity==='payments'&&duplicate(['name']))throw new Failure(409,'Invoice/payment reference already exists');
 if(KIND==='repaircommons'&&entity==='parts'&&state.faults.find((f:any)=>f.id===record.faultId).category!==record.category)throw new Failure(400,'Part and fault must belong to the same device family');
 if(KIND==='repaircommons'&&entity==='likelihoods'&&duplicate(['faultId','symptom']))throw new Failure(409,'Likelihood rule already exists');
 if(KIND==='foodrescue-dispatch'){if(entity==='supplies'&&Date.parse(record.expiresAt)<=Date.parse(record.readyAt))throw new Failure(400,'Deadline must follow pickup opening');if(entity==='demands'){if(Date.parse(record.closesAt)<=Date.parse(record.opensAt))throw new Failure(400,'Closing must follow opening');const prev=state.demands.find((r:any)=>r.id===existingId);if(prev&&record.quantity<prev.served+prev.reserved)throw new Failure(409,'Demand cannot fall below fulfilled and reserved units')}}
 if(existingId&&state.plans.some((p:any)=>['RESERVED','CONFIRMED'].includes(p.status)&&((p.result.recommendation?.facilityId===existingId)||(p.result.recommendation?.lines?.some((l:any)=>l.stockId===existingId||l.requestId===existingId)))))throw new Failure(409,'Settle or release active reservations before editing this record');
}
export async function appendEvent(s:any,action:string,detail:any,actor:string,now=Date.now()){
 if(s.events.length>=300)throw new Failure(409,'Demo history limit: 300 mutations');const previous=s.events.at(-1)?.hash??'GENESIS';const event={id:crypto.randomUUID(),action,detail,actor,createdAt:new Date(now).toISOString(),previous};const bytes=new TextEncoder().encode(JSON.stringify(event));const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');s.events.push({...event,hash});
}
export async function auditValid(events:any[]){let previous='GENESIS';for(const e of events){const {hash,...body}=e;if(body.previous!==previous)return false;const digest=[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(body))))].map(x=>x.toString(16).padStart(2,'0')).join('');if(digest!==hash)return false;previous=hash}return true}
export function mutate(s:any,raw:any,now=Date.now()){
 const base={action:z.string(),version:z.number().int().min(0)};const op=raw.action;let result:any;
 if(['analyze','snapshot','reserve'].includes(op)){const b=z.object({...base,parameters:z.record(z.unknown()),id:z.string().uuid().optional()}).strict().parse(raw);const p=validate(config.parameters,b.parameters,s);if(op==='reserve'){if(!config.reservable||!b.id)throw new Failure(400,'Reservation ID required');try{result=reserve(KIND,s,b.id,p,now)}catch(e:any){throw new Failure(409,e.message)}}else{try{result=analyze(KIND,s,p,now)}catch(e:any){throw new Failure(400,e.message)}if(op==='analyze')return {readonly:true,result};if(s.snapshots.length>=100)throw new Failure(409,'Demo limit: 100 snapshots');s.snapshots.unshift({id:crypto.randomUUID(),parameters:p,result,createdAt:new Date(now).toISOString()})}}
 else if(['add','edit'].includes(op)){const b=z.object({...base,entity:z.string(),record:z.record(z.unknown()),id:z.string().optional()}).strict().parse(raw);const entity=config.entities.find((e:any)=>e.key===b.entity);if(!entity)throw new Failure(400,'Unknown record type');const rows=s[entity.key];if(op==='add'&&rows.length>=100)throw new Failure(409,'Demo limit: 100 records per type');const index=rows.findIndex((r:any)=>r.id===b.id);if(op==='edit'&&index<0)throw new Failure(404,'Record not found');const r=validate(entity.fields,b.record,s);verifyRecord(entity.key,r,s,op==='edit'?b.id:undefined);result=op==='edit'?{...rows[index],...r}:{...r,id:crypto.randomUUID(),reserved:0,occupied:0,served:0,status:'ACTIVE'};if(op==='edit')rows[index]=result;else rows.push(result)}
 else if(op==='settle'){const b=z.object({...base,id:z.string().uuid(),status:z.enum(['CONFIRMED','CANCELLED','EXITED'])}).strict().parse(raw);try{const changed=settle(KIND,s,b.id,b.status);result={id:b.id,status:b.status};if(!changed)return {readonly:true,result}}catch(e:any){throw new Failure(409,e.message)}}
 else if(op==='review'){const b=z.object({...base,snapshotId:z.string().uuid(),note:z.string().trim().min(5).max(1000),status:z.enum(['FOLLOW_UP','REVIEWED'])}).strict().parse(raw);if(!s.snapshots.some((r:any)=>r.id===b.snapshotId))throw new Failure(404,'Snapshot not found');result={...b,id:crypto.randomUUID(),createdAt:new Date(now).toISOString()};s.reviews.unshift(result)}
 else throw new Failure(400,'Unknown action');return {readonly:false,result,action:op};
}
